### ISSUE TITLE
training cost

### ISSUE THREAD

**Issue by aidenjhwu** [JeongsooP/RGB-no-more#2]
Hello, I think this work is really valuable and I want to follow it and do some improvement.
I wonder how long does it spend to train from scratch, so that I can estimate my cost to do experiment.

**Comment by JeongsooP** [comment]
Hi, thanks for your interest.
Using 4x A40 GPUs and 16x CPU threads: 
- JPEG-S for 90 epochs (no mixed precision): about 17.5 hrs
- JPEG SwinV2 for 90 epochs (using mixed precision): about 36.2 hrs

I also tried using 8x 2080Tis and 32x CPU threads:
- JPEG-S for 90 epochs (no mixed precision): about 19.5 hrs
- JPEG-S for 90 epochs (using mixed precision): about 12 hrs

Hope it helps!
