### ISSUE TITLE
CMake Configurations to add pybind11 to work with C++

### ISSUE THREAD

**Issue by deanAirre** [JeongsooP/RGB-no-more#3]
Hello, 

Good evening Mr, Park. I am really interested in developing your findings in your research to pursue faster and lighter Transformer system. However, from the look of things, there are issues in which I want to ask to you personally;
1. It seems that your system requires CMakeList, thus implying CMakeLists.txt, should've exist within the folder to make Pybind11 and Torch work together interconnectedly between C++ and Python codes. In this case is there any specific guide to write CMakeLists according to your preferences and what you used in your research?

2. I really appreciate that you add pretrained model to your work, so some us don't have to train things from the start with ImageNet datasets anymore and starts using our own dataset to compare it with your existing model, however it seems that the guide in using it isn't attached and I don't see anywhere "I can plug my models into your system". Is there any recommended steps you recommend to help the users tests your pretrain models?

3. Do you recommend running your method in CPU only system?

Best regards,
Sean.

**Comment by JeongsooP** [comment]
Hello Sean,

1. I believe you should be able to install without CMakeLists.txt through `pip`. Please check the steps on *Compile dct_manip -- a modified libjpeg handler*.
2. You can load the model through `--loadpath` argument. Please check 'Arguments' under 'Pipeline' for more options.
3. Sorry, I don't have any advice on running this on CPU-only system.

Thanks!
